<?php require '/srv/http/TEMPLATES/dev-header.php';?>
<?php require '/srv/http/TEMPLATES/navbar.php'; ?>

<div class="col-md-1"></div>

<div class="col-md-10">
	<div class="panel panel-default">
	   <div class="panel-heading"><!-- _____________PANEL HEADING______________ -->
	      <a class="title"><h2>Data</h2></a>
         <p>data generated by the application</p>
         <a href="https://github.com/jpchanson/A.R.C./tree/CurrentState" class="btn btn-primary" target="_blank">A.R.C. Applicaion - SourceCode</a>
         <a href="https://github.com/jpchanson/ArcServer" class="btn btn-primary" target="_blank" >A.R.C. Server - SourceCode</a>

                 <nav> 
            <ul class="pagination"> 
               <li> 
                  <a href="/CONTENT/dev/JPCH/ARC/dev-ARC-1.php" aria-label="Previous"> 
                     <span aria-hidden="true">&laquo;</span> 
                  </a> 
               </li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-1.php">1</a></li> 
               <li class="active" ><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-2.php">2</a></li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-3.php">3</a></li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-4.php">4</a></li> 
               <li> 
                  <a href="/CONTENT/dev/JPCH/ARC/dev-ARC-3.php" aria-label="Next"> 
                     <span aria-hidden="true">&raquo;</span> 
                  </a> 
               </li> 
            </ul> 
         </nav>
                                 <!-- _____________ENDOF PANEL HEADING______________ -->
                                 <!-- _____________PANEL BODY______________ -->
	   </div>
		<div class="panel-body">
         <h3>Application Data</h3>
         <p>Given the nature of the application, no data really needed to be stored directly on the device, at least, not at the
         current state of development. But in order to be classed as a social networking application, it must definately generate
         data. Post data to be specific (post content, post title, etc). This is done in the PostActivity(shown below).
         </p>
         <img class="img-responsive" src="/RESOURCES/devPics/JPCH/ARC/postView.png"></img>
         <p>
         TestWorld is a test version of the presenter stored in the Testing package, it made it easier to test the application
         as the server is only available on the local brunel network, which i am unable to gain access to from home.
         </p>
         
         <h3>Server Data</h3>
         <p>
         The data created by the postView is stored in a MySql to be used by the app, which corresponds to the ER diagram shown below.
         I was responsible for the design of the database, and tried to ensure that it remained in 3rd normal form, as well as attempting
         to make the database as future proof as possible. With this in mind I implemented provisions for functionality not yet implemented
         in my app (or that of other group members) such as ability to create friend relationships, or view friend data.
         </p>
         <img class="img-responsive" src="/RESOURCES/devPics/JPCH/ARC/Database_ERD_v3.png" style="background:lightgrey;"></img>      
            
         <nav> 
            <ul class="pagination"> 
               <li> 
                  <a href="/CONTENT/dev/JPCH/ARC/dev-ARC-1.php" aria-label="Previous"> 
                     <span aria-hidden="true">&laquo;</span> 
                  </a> 
               </li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-1.php">1</a></li> 
               <li class="active" ><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-2.php">2</a></li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-3.php">3</a></li> 
               <li><a href="/CONTENT/dev/JPCH/ARC/dev-ARC-4.php">4</a></li> 
               <li> 
                  <a href="/CONTENT/dev/JPCH/ARC/dev-ARC-3.php" aria-label="Next"> 
                     <span aria-hidden="true">&raquo;</span> 
                  </a> 
               </li> 
            </ul> 
         </nav>
         </div>                        <!-- _____________ENDOF PANEL BODY ______________ -->
                                 <!-- _____________PANEL FOOTER______________ -->
      <div class="panel-footer">
         Jan Hanson: 1339404
      </div>                     <!-- _____________ENDOF PANEL FOOTER______________ -->
   </div>
</div>

<?php require '/srv/http/TEMPLATES/footer.php'; ?>